version=0.1
 [default.global.parameters]
 stack_name = "appsync-dynamo-demo-stack"
 
 [default.deploy.parameters]
 confirm_changeset = true
 capabilities = "CAPABILITY_IAM"
 region = "us-east-1"
 image_repositories = []

 [default.build.parameters]
 no_beta_features = false
